# application.yml
spring:
  server:
    tomcat:
      max-swallow-size: -1
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/auth/google/redirect
            client-id: 99898080219-a77mbtbcrdlmt8ssmnl4dicqv58fcr14.apps.googleusercontent.com
            client-secret: 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
  datasource:
    url: jdbc:mysql://localhost:3306/ploop_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: plogger
    password: plogger1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000  # 30초까지 대기
      initialization-fail-timeout: -1  # 실패해도 재시도
  config:
    import: optional:application-secret.yml
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  jpa:
    hibernate:
      ddl-auto: update   # 개발 중엔 update, 운영 땐 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.example.ploop_backend: DEBUG

google:
    clientId: 226017564204-otrfeo1q0t7gotr7vaemchggh5ts3vb9.apps.googleusercontent.com

jwt:
  secret: bXktc3VwZXItc2VjdXJlLXNlY3JldC1rZXktZm9yLXRva2VuIQ==