spring:
  data:
    redis:
      username: default
      password: 1234
  datasource:
    password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 99898080219-a77mbtbcrdlmt8ssmnl4dicqv58fcr14.apps.googleusercontent.com
            client-secret: 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
jwt:
  secret: bXktc3VwZXItc2VjdXJlLXNlY3JldC1rZXktZm9yLXRva2VuIQ==

r2:
  endpoint: https://d178f93576947bd0a52303dfa4e15768.r2.cloudflarestorage.com
  access-key: b99997017b81bb5083528f8dc50903c1
  secret-key: 6d0e72619fa6071c496f1bb0b8e405e9ec527eb13cf9b5433d712a14bc7cb8f9
  bucket: ploop

google:
  clientId: 226017564204-otrfeo1q0t7gotr7vaemchggh5ts3vb9.apps.googleusercontent.com

