spring:
  server:
    tomcat:
      max-swallow-size: -1
  datasource:
    url: jdbc:mysql://mysql:3306/ploopdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: plogger
    password: plogger1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    profiles:
      active: local
    hikari:
      connection-timeout: 30000  # 30초까지 대기
      initialization-fail-timeout: -1  # 실패해도 재시도
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  jpa:
    hibernate:
      ddl-auto: update   # 개발 중엔 update, 운영 땐 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE  # 파라미터까지 출력됨

google:
    clientId: 226017564204-otrfeo1q0t7gotr7vaemchggh5ts3vb9.apps.googleusercontent.com

jwt:
  secret: bXktc3VwZXItc2VjdXJlLXNlY3JldC1rZXktZm9yLXRva2VuIQ==