spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/auth/google/redirect
            client-id: 99898080219-a77mbtbcrdlmt8ssmnl4dicqv58fcr14.apps.googleusercontent.com
            client-secret: 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
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ploop
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver