# application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/auth/google/redirect
            client-id: 99898080219-a77mbtbcrdlmt8ssmnl4dicqv58fcr14.apps.googleusercontent.com
            client-secret: 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
  datasource:
    url: jdbc:mysql://mysql:3307/ploggingdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: plogger
    password: plogger1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:application-secret.yml

  jpa:
    hibernate:
      ddl-auto: update   # 개발 중엔 update, 운영 땐 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  logging:
    level:
      org.hibernate.SQL: debug

google:
    clientId: 226017564204-otrfeo1q0t7gotr7vaemchggh5ts3vb9.apps.googleusercontent.com

jwt:
  secret: bXktc3VwZXItc2VjdXJlLXNlY3JldC1rZXktZm9yLXRva2VuIQ==