spring:
  profiles:
    active: secret
  server:
    tomcat:
      max-swallow-size: -1
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/auth/google/redirect
  datasource:
    url: jdbc:mysql://localhost:3306/ploop # ploop_db
    username: root # plogger
    password: 1234 # plogger1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000  # 30초까지 대기
      initialization-fail-timeout: -1  # 실패해도 재시도
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  jpa:
    hibernate:
      ddl-auto: create # 개발 중에는 db 구조 변경이 잦으므로 create로 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE  # 파라미터까지 출력됨
jwt:
  secret: bXktc3VwZXItc2VjdXJlLXNlY3JldC1rZXktZm9yLXRva2VuIQ==
