# application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/auth/google/redirect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ploop
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:application-secret.yml
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update   # 개발 중엔 update, 운영 땐 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  logging:
    level:
      org.hibernate.SQL: debug

